### ISSUE TITLE
'View Results' hidden until refresh after submitting poll/survey as staff

### ISSUE THREAD

**Issue by itsbenweeks** [mckinseyacademy/xblock-poll#14] opened 2015-07-20 16:08 UTC
The `View Results` button disappears after a staff member submits anything. It does reappear upon page reload, though.
1. Create a poll or survey. 
2. Submit a response as a staff member in lms.

**Comment by antoviaque** [comment] 2015-07-20 16:29
Thank you for the bug reports! I'll try to test these when I get a chance, to confirm them.

Btw, if you are in a position to contribute fixes, we gladly welcome PRs : )

**Comment by e-kolpakov** [comment] 2015-08-19 10:15
@itsbenweeks I've just looked into this issue and I'm afraid I can't reproduce it. At least current behavior looks pretty much valid to me - "View Results" button disappear when the results are displayed. Could you please provide a bit more info about that:
1. Poll settings, especially "Private Results" and "Maximum Submissions"
2. More detailed scenario that leads to an error (+ actual and expected behavior).

Ideally these should be a course export tarball (but please don't use your actual course with hundreds of units) and a video recording, but textual description should be enough.

**Comment by antoviaque** [comment] 2015-08-24 12:26
@itsbenweeks Since we can't reproduce that issue anymore, without answer from you I'm closing this issue. Can you comment here if you still have it, along with the details @e-kolpakov is asking? Thank you!

**Closed as completed by antoviaque** 2015-08-24 12:26 UTC
